/*
  # Create API Wizard System (Phase 5)

  1. New Tables
    - `custom_api_definitions` - User-defined API connections via the API Wizard
      - `id` (uuid, primary key)
      - `team_id` (uuid) - Team that created this
      - `created_by` (uuid) - User who created it
      - `api_name` (text) - Display name (e.g. "My CRM API")
      - `api_slug` (text) - URL-safe identifier
      - `base_url` (text) - API base URL
      - `description` (text) - What this API provides
      - `auth_type` (text) - api_key, bearer_token, oauth2, basic_auth, none
      - `auth_config` (jsonb) - Auth configuration (encrypted at rest)
      - `api_docs_url` (text) - Link to API documentation
      - `openapi_spec` (jsonb) - OpenAPI/Swagger spec if available
      - `status` (text) - draft, pending_review, approved, active, rejected, disabled
      - `approval_notes` (text) - Admin review notes
      - `approved_by` (uuid) - Admin who approved
      - `approved_at` (timestamptz)
      - `category` (text) - Category for organization
      - `icon_url` (text) - Custom icon
      - `rate_limit_rpm` (integer) - Max requests per minute
      - `metadata` (jsonb) - Extra settings
      - `created_at` / `updated_at` (timestamptz)

    - `custom_api_endpoints` - Individual API endpoints/tools
      - `id` (uuid, primary key)
      - `api_definition_id` (uuid) - Parent API definition
      - `team_id` (uuid) - Team context
      - `endpoint_name` (text) - Technical name
      - `display_name` (text) - Human-friendly name
      - `description` (text) - What this endpoint does
      - `http_method` (text) - GET, POST, PUT, DELETE
      - `path` (text) - URL path (e.g. "/contacts/{id}")
      - `input_schema` (jsonb) - Parameter schema
      - `output_schema` (jsonb) - Response schema
      - `headers` (jsonb) - Custom headers
      - `is_read_only` (boolean) - Read-only flag
      - `is_enabled` (boolean) - Active/disabled
      - `requires_approval` (boolean) - Per-execution approval
      - `ai_generated` (boolean) - Was this auto-generated by the wizard
      - `usage_count` (integer) - Times called
      - `last_used_at` (timestamptz) - Last execution
      - `created_at` / `updated_at` (timestamptz)

  2. Security
    - RLS enabled on all tables
    - Team members can view their team's API definitions
    - Only admins and creators can modify definitions
    - Approval workflow enforced via status field

  3. Notes
    - API definitions start in 'draft' status
    - Admins approve before they become 'active'
    - Rate limiting enforced at edge function level
    - Auth configs should be encrypted at rest
*/

-- Custom API Definitions table
CREATE TABLE IF NOT EXISTS custom_api_definitions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL REFERENCES teams(id),
  created_by uuid NOT NULL REFERENCES auth.users(id),
  api_name text NOT NULL,
  api_slug text NOT NULL,
  base_url text NOT NULL,
  description text,
  auth_type text NOT NULL DEFAULT 'api_key' CHECK (auth_type IN (
    'api_key', 'bearer_token', 'oauth2', 'basic_auth', 'none'
  )),
  auth_config jsonb DEFAULT '{}'::jsonb,
  api_docs_url text,
  openapi_spec jsonb,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN (
    'draft', 'pending_review', 'approved', 'active', 'rejected', 'disabled'
  )),
  approval_notes text,
  approved_by uuid REFERENCES auth.users(id),
  approved_at timestamptz,
  category text DEFAULT 'custom',
  icon_url text,
  rate_limit_rpm integer DEFAULT 60,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(team_id, api_slug)
);

CREATE INDEX IF NOT EXISTS idx_custom_api_defs_team_id ON custom_api_definitions(team_id);
CREATE INDEX IF NOT EXISTS idx_custom_api_defs_status ON custom_api_definitions(status);
CREATE INDEX IF NOT EXISTS idx_custom_api_defs_created_by ON custom_api_definitions(created_by);

ALTER TABLE custom_api_definitions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Team members can view team API definitions"
  ON custom_api_definitions FOR SELECT
  TO authenticated
  USING (
    team_id IN (SELECT team_id FROM users WHERE id = auth.uid())
  );

CREATE POLICY "Team members can create API definitions"
  ON custom_api_definitions FOR INSERT
  TO authenticated
  WITH CHECK (
    created_by = auth.uid()
    AND team_id IN (SELECT team_id FROM users WHERE id = auth.uid())
  );

CREATE POLICY "Creators and admins can update API definitions"
  ON custom_api_definitions FOR UPDATE
  TO authenticated
  USING (
    team_id IN (SELECT team_id FROM users WHERE id = auth.uid())
    AND (
      created_by = auth.uid()
      OR (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
    )
  )
  WITH CHECK (
    team_id IN (SELECT team_id FROM users WHERE id = auth.uid())
    AND (
      created_by = auth.uid()
      OR (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
    )
  );

CREATE POLICY "Admins can delete API definitions"
  ON custom_api_definitions FOR DELETE
  TO authenticated
  USING (
    team_id IN (SELECT team_id FROM users WHERE id = auth.uid())
    AND (
      created_by = auth.uid()
      OR (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
    )
  );

CREATE POLICY "Super admins can view all API definitions"
  ON custom_api_definitions FOR SELECT
  TO authenticated
  USING (
    (auth.jwt() -> 'user_metadata' ->> 'email') IN (
      'clay@rockethub.ai', 'john@rockethub.ai'
    )
  );

-- Custom API Endpoints table
CREATE TABLE IF NOT EXISTS custom_api_endpoints (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  api_definition_id uuid NOT NULL REFERENCES custom_api_definitions(id) ON DELETE CASCADE,
  team_id uuid NOT NULL REFERENCES teams(id),
  endpoint_name text NOT NULL,
  display_name text NOT NULL,
  description text,
  http_method text NOT NULL DEFAULT 'GET' CHECK (http_method IN (
    'GET', 'POST', 'PUT', 'PATCH', 'DELETE'
  )),
  path text NOT NULL,
  input_schema jsonb DEFAULT '{}'::jsonb,
  output_schema jsonb DEFAULT '{}'::jsonb,
  headers jsonb DEFAULT '{}'::jsonb,
  is_read_only boolean DEFAULT true,
  is_enabled boolean DEFAULT true,
  requires_approval boolean DEFAULT false,
  ai_generated boolean DEFAULT false,
  usage_count integer DEFAULT 0,
  last_used_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(api_definition_id, endpoint_name)
);

CREATE INDEX IF NOT EXISTS idx_custom_api_endpoints_api_id ON custom_api_endpoints(api_definition_id);
CREATE INDEX IF NOT EXISTS idx_custom_api_endpoints_team_id ON custom_api_endpoints(team_id);
CREATE INDEX IF NOT EXISTS idx_custom_api_endpoints_enabled ON custom_api_endpoints(is_enabled) WHERE is_enabled = true;

ALTER TABLE custom_api_endpoints ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Team members can view team API endpoints"
  ON custom_api_endpoints FOR SELECT
  TO authenticated
  USING (
    team_id IN (SELECT team_id FROM users WHERE id = auth.uid())
  );

CREATE POLICY "Team members can create API endpoints"
  ON custom_api_endpoints FOR INSERT
  TO authenticated
  WITH CHECK (
    team_id IN (SELECT team_id FROM users WHERE id = auth.uid())
  );

CREATE POLICY "Creators and admins can update API endpoints"
  ON custom_api_endpoints FOR UPDATE
  TO authenticated
  USING (
    team_id IN (SELECT team_id FROM users WHERE id = auth.uid())
    AND (
      EXISTS (
        SELECT 1 FROM custom_api_definitions
        WHERE id = custom_api_endpoints.api_definition_id
        AND (created_by = auth.uid() OR (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin')
      )
    )
  )
  WITH CHECK (
    team_id IN (SELECT team_id FROM users WHERE id = auth.uid())
  );

CREATE POLICY "Admins can delete API endpoints"
  ON custom_api_endpoints FOR DELETE
  TO authenticated
  USING (
    team_id IN (SELECT team_id FROM users WHERE id = auth.uid())
    AND (
      EXISTS (
        SELECT 1 FROM custom_api_definitions
        WHERE id = custom_api_endpoints.api_definition_id
        AND (created_by = auth.uid() OR (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin')
      )
    )
  );

CREATE POLICY "Super admins can view all API endpoints"
  ON custom_api_endpoints FOR SELECT
  TO authenticated
  USING (
    (auth.jwt() -> 'user_metadata' ->> 'email') IN (
      'clay@rockethub.ai', 'john@rockethub.ai'
    )
  );

-- Function to get available tools for a team (both MCP and custom API)
CREATE OR REPLACE FUNCTION get_team_available_tools(p_team_id uuid)
RETURNS jsonb AS $$
DECLARE
  v_result jsonb;
BEGIN
  SELECT jsonb_build_object(
    'mcp_tools', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'id', t.id,
        'tool_name', t.tool_name,
        'display_name', t.display_name,
        'description', t.description,
        'input_schema', t.input_schema,
        'category', t.category,
        'is_read_only', t.is_read_only,
        'server_name', s.name,
        'server_type', s.server_type,
        'source', 'mcp'
      ))
      FROM mcp_tools t
      JOIN mcp_servers s ON s.id = t.server_id
      WHERE t.team_id = p_team_id
        AND t.is_enabled = true
        AND s.status = 'active'
    ), '[]'::jsonb),
    'custom_api_tools', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'id', e.id,
        'tool_name', e.endpoint_name,
        'display_name', e.display_name,
        'description', e.description,
        'input_schema', e.input_schema,
        'http_method', e.http_method,
        'path', e.path,
        'is_read_only', e.is_read_only,
        'api_name', d.api_name,
        'base_url', d.base_url,
        'source', 'custom_api'
      ))
      FROM custom_api_endpoints e
      JOIN custom_api_definitions d ON d.id = e.api_definition_id
      WHERE e.team_id = p_team_id
        AND e.is_enabled = true
        AND d.status = 'active'
    ), '[]'::jsonb),
    'total_tools', (
      SELECT COUNT(*)
      FROM mcp_tools t
      JOIN mcp_servers s ON s.id = t.server_id
      WHERE t.team_id = p_team_id AND t.is_enabled = true AND s.status = 'active'
    ) + (
      SELECT COUNT(*)
      FROM custom_api_endpoints e
      JOIN custom_api_definitions d ON d.id = e.api_definition_id
      WHERE e.team_id = p_team_id AND e.is_enabled = true AND d.status = 'active'
    )
  ) INTO v_result;

  RETURN COALESCE(v_result, '{"mcp_tools": [], "custom_api_tools": [], "total_tools": 0}'::jsonb);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;